#!/usr/bin/env python3
"""Generate LiquidGlassIconPreviews.gen.h from PNG files in this directory.

Writes one C byte array per PNG plus a lookup table keyed by
"<iconID>/<variant>" strings (e.g. "jryng/default"). The tweak loads the
images as NSData via dataWithBytesNoCopy:length:freeWhenDone:NO so the
backing storage stays in the dylib's read-only data segment.
"""
from __future__ import annotations

import os
import sys

ICONS = ["jryng", "jryng-alt", "igerman00", "metalnakls"]
VARIANTS = ["default", "dark", "clear-light", "clear-dark"]


def sanitize(name: str) -> str:
    return name.replace("-", "_")


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate_header.py <output_header_path>", file=sys.stderr)
        return 2

    out_path = sys.argv[1]
    src_dir = os.path.dirname(os.path.abspath(__file__))

    rows = []
    arrays = []

    for icon in ICONS:
        for variant in VARIANTS:
            filename = f"{icon}-{variant}.png"
            src = os.path.join(src_dir, filename)
            if not os.path.isfile(src):
                print(f"missing preview asset: {src}", file=sys.stderr)
                return 1

            with open(src, "rb") as fp:
                data = fp.read()

            symbol = f"kLGPreview_{sanitize(icon)}_{sanitize(variant)}"
            hex_bytes = ", ".join(f"0x{b:02x}" for b in data)
            arrays.append(
                f"static const unsigned char {symbol}[] = {{\n{hex_bytes}\n}};\n"
            )
            rows.append((icon, variant, symbol, len(data)))

    with open(out_path, "w") as fp:
        fp.write("// Auto-generated by Resources/LiquidGlassIconPreviews/generate_header.py.\n")
        fp.write("// Do not edit by hand. Regenerate by running `make` (the makefile invokes the script).\n")
        fp.write("#pragma once\n\n")
        fp.write("#include <stddef.h>\n\n")

        for blob in arrays:
            fp.write(blob)
            fp.write("\n")

        fp.write("typedef struct {\n")
        fp.write("    const char *iconID;\n")
        fp.write("    const char *variant;\n")
        fp.write("    const unsigned char *bytes;\n")
        fp.write("    size_t length;\n")
        fp.write("} LGPreviewEntry;\n\n")

        fp.write("static const LGPreviewEntry kLGPreviewEntries[] = {\n")
        for icon, variant, symbol, length in rows:
            fp.write(f'    {{ "{icon}", "{variant}", {symbol}, sizeof({symbol}) }},\n')
        fp.write("};\n\n")
        fp.write(f"static const size_t kLGPreviewEntryCount = {len(rows)};\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
