#!/usr/bin/env python3
"""Generate LiquidGlassIconPreviews.gen.h from PNG files in this directory.

Encodes each PNG as a base64 ASCII string and emits a lookup table keyed by
"<iconID>/<variant>". The tweak decodes each string lazily on first display
(and caches the resulting UIImage), so source size and compile time are much
smaller than a raw hex byte-array embedding.
"""
from __future__ import annotations

import base64
import os
import sys
import textwrap

ICONS = ["jryng", "jryng-alt", "igerman00", "metalnakls"]
VARIANTS = ["default", "dark", "clear-light", "clear-dark"]


def sanitize(name: str) -> str:
    return name.replace("-", "_")


def chunked(s: str, width: int = 76):
    for i in range(0, len(s), width):
        yield s[i:i + width]


def main() -> int:
    if len(sys.argv) != 2:
        print("usage: generate_header.py <output_header_path>", file=sys.stderr)
        return 2

    out_path = sys.argv[1]
    src_dir = os.path.dirname(os.path.abspath(__file__))

    rows = []
    arrays = []

    for icon in ICONS:
        for variant in VARIANTS:
            src = os.path.join(src_dir, icon, f"{variant}.png")
            if not os.path.isfile(src):
                print(f"missing preview asset: {src}", file=sys.stderr)
                return 1

            with open(src, "rb") as fp:
                data = fp.read()

            b64 = base64.b64encode(data).decode("ascii")
            symbol = f"kLGPreviewB64_{sanitize(icon)}_{sanitize(variant)}"
            # Emit one C string literal per chunked line. Adjacent string
            # literals concatenate at compile time, so this is a single
            # const char *.
            literal_lines = "\n".join(f'    "{chunk}"' for chunk in chunked(b64))
            arrays.append(
                f"static const char {symbol}[] =\n{literal_lines};\n"
            )
            rows.append((icon, variant, symbol, len(data)))

    with open(out_path, "w") as fp:
        fp.write("// Auto-generated by Resources/LiquidGlassIconPreviews/generate_header.py.\n")
        fp.write("// Do not edit by hand. Regenerate with `make lg-previews`.\n")
        fp.write("#pragma once\n\n")
        fp.write("#include <stddef.h>\n\n")

        for blob in arrays:
            fp.write(blob)
            fp.write("\n")

        fp.write("typedef struct {\n")
        fp.write("    const char *iconID;\n")
        fp.write("    const char *variant;\n")
        fp.write("    const char *base64;\n")
        fp.write("    size_t decodedLength;\n")
        fp.write("} LGPreviewEntry;\n\n")

        fp.write("static const LGPreviewEntry kLGPreviewEntries[] = {\n")
        for icon, variant, symbol, decoded_length in rows:
            fp.write(f'    {{ "{icon}", "{variant}", {symbol}, {decoded_length} }},\n')
        fp.write("};\n\n")
        fp.write(f"static const size_t kLGPreviewEntryCount = {len(rows)};\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
